### ISSUE TITLE
Suitcase does not support printing

### ISSUE THREAD

**Issue by Kristi-Elmore** [isubit/suitcase#24]
No print.css file associated with theme, printed out page is not ideal and includes a lot of information not needed.

I'm working on a very clean css file for this, with only the basic information printed...will upload when done.

**Comment by rlfrahm** [comment]
`suitcase.css` already contains a `@media print {}` block. Why not just put print declaratives in there?

**Comment by Kristi-Elmore** [comment]
I guess I didn't realize that it did.  I'll add the print declarations to that and resubmit.  Sorry - should have looked for that!

Kristi Elmore
ISU Extension IT

**Comment by rlfrahm** [comment]
Firstly, thanks for the help!

Before we commit code we should first discuss how we see print being used in Suitcase and what elements should be displayed in a print layout. My initial thought is to override styling for things like links, background colors and fonts. A minimalistic approach to print would be ideal for the platform. See image below which is a view of Suitcase through the Safari reader tool.

![screen shot 2015-07-30 at 9 04 16 am](https://cloud.githubusercontent.com/assets/5338740/8984818/a7c0ac7a-3699-11e5-8794-a0d0627f5330.png)

We could take this approach and add the ISU nameplate, the department title & and the site name to the top. Then also switch to serif font for print.

What do you think? Does this work for your use cases?

**Comment by Kristi-Elmore** [comment]
I did ask for information like this before I started, but was told nothing had been discussed at that time, so I just tried to pull out pretty much everything but the actual content.  I'll take another look and resubmit with the @media selector.

Thanks for providing more information.

**Comment by rlfrahm** [comment]
@Kristi-Elmore, checkout the `lugg344` branch which contains commit b4b7485 and tell me what you think.

**Comment by Kristi-Elmore** [comment]
@rlfrahm  Minus the ISU nameplate not showing up since it's white - it looks fine to me.

**Comment by rlfrahm** [comment]
Yes that is a little bit of a problem.. We will need to spoof this a little bit. One way to do this is to show an alternate image.

**Comment by njbooher** [comment]
Fixed. https://github.com/isubit/suitcase/pull/51
